// <auto-generated />
using System;
using Freshmart.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Freshmart.Infrastructure.Migrations
{
    [DbContext(typeof(FreshmartDbContext))]
    [Migration("20250411024545_AddProductSeedData")]
    partial class AddProductSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Freshmart.Infrastructure.Data.DbEntities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991873"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dfd92623-8828-4d7f-ba7f-d25b5fbfb978",
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "admin@freshmart.com",
                            EmailConfirmed = true,
                            FirstName = "Admin",
                            ImageUrl = "/images/default-profile.jpg",
                            IsDeleted = false,
                            LastName = "User",
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@FRESHMART.COM",
                            NormalizedUserName = "ADMIN@FRESHMART.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEH8K562A1KbQYmrHj9PZ3VsosoF+OKRZWkF3rJihV+LsDn0bPLLnOIaEcCAwyBdUvw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c9d4c053-49b6-410c-bc78-2d54a9991876",
                            TwoFactorEnabled = false,
                            UserName = "admin@freshmart.com"
                        });
                });

            modelBuilder.Entity("Freshmart.Infrastructure.Data.DbEntities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh fruits",
                            ImageUrl = "/images/categories/fruits.jpg",
                            IsDeleted = false,
                            Name = "Fruits"
                        },
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991871"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh vegetables",
                            ImageUrl = "/images/categories/vegetables.jpg",
                            IsDeleted = false,
                            Name = "Vegetables"
                        },
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991872"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Dairy products",
                            ImageUrl = "/images/categories/dairy.jpg",
                            IsDeleted = false,
                            Name = "Dairy"
                        });
                });

            modelBuilder.Entity("Freshmart.Infrastructure.Data.DbEntities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Rating")
                        .HasColumnType("numeric");

                    b.Property<int>("ReviewCount")
                        .HasColumnType("integer");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("products", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7a4b1c53-49b6-410c-bc78-2d54a9991880"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh red apples",
                            ImageUrl = "/images/products/apple.jpg",
                            IsDeleted = false,
                            Name = "Apple",
                            Price = 1.99m,
                            Rating = 4.5m,
                            ReviewCount = 28,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = new Guid("7a4b1c53-49b6-410c-bc78-2d54a9991881"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh yellow bananas",
                            ImageUrl = "/images/products/banana.jpg",
                            IsDeleted = false,
                            Name = "Banana",
                            Price = 0.99m,
                            Rating = 4.8m,
                            ReviewCount = 32,
                            StockQuantity = 150
                        },
                        new
                        {
                            Id = new Guid("7a4b1c53-49b6-410c-bc78-2d54a9991882"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991870"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh juicy oranges",
                            ImageUrl = "/images/products/orange.jpg",
                            IsDeleted = false,
                            Name = "Orange",
                            Price = 1.49m,
                            Rating = 4.6m,
                            ReviewCount = 24,
                            StockQuantity = 80
                        },
                        new
                        {
                            Id = new Guid("7a4b1c53-49b6-410c-bc78-2d54a9991883"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991871"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh organic carrots",
                            ImageUrl = "/images/products/carrot.jpg",
                            IsDeleted = false,
                            Name = "Carrot",
                            Price = 1.29m,
                            Rating = 4.4m,
                            ReviewCount = 18,
                            StockQuantity = 120
                        },
                        new
                        {
                            Id = new Guid("7a4b1c53-49b6-410c-bc78-2d54a9991884"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991871"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh green broccoli",
                            ImageUrl = "/images/products/broccoli.jpg",
                            IsDeleted = false,
                            Name = "Broccoli",
                            Price = 1.99m,
                            Rating = 4.3m,
                            ReviewCount = 15,
                            StockQuantity = 70
                        },
                        new
                        {
                            Id = new Guid("7a4b1c53-49b6-410c-bc78-2d54a9991885"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991871"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh leafy spinach",
                            ImageUrl = "/images/products/spinach.jpg",
                            IsDeleted = false,
                            Name = "Spinach",
                            Price = 2.49m,
                            Rating = 4.7m,
                            ReviewCount = 22,
                            StockQuantity = 60
                        },
                        new
                        {
                            Id = new Guid("7a4b1c53-49b6-410c-bc78-2d54a9991886"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991872"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fresh whole milk",
                            ImageUrl = "/images/products/milk.jpg",
                            IsDeleted = false,
                            Name = "Milk",
                            Price = 2.99m,
                            Rating = 4.9m,
                            ReviewCount = 37,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = new Guid("7a4b1c53-49b6-410c-bc78-2d54a9991887"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991872"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Premium cheddar cheese",
                            ImageUrl = "/images/products/cheese.jpg",
                            IsDeleted = false,
                            Name = "Cheese",
                            Price = 3.99m,
                            Rating = 4.8m,
                            ReviewCount = 29,
                            StockQuantity = 40
                        },
                        new
                        {
                            Id = new Guid("7a4b1c53-49b6-410c-bc78-2d54a9991888"),
                            CategoryId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991872"),
                            CreatedAt = new DateTime(2023, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Natural Greek yogurt",
                            ImageUrl = "/images/products/yogurt.jpg",
                            IsDeleted = false,
                            Name = "Yogurt",
                            Price = 1.79m,
                            Rating = 4.6m,
                            ReviewCount = 26,
                            StockQuantity = 90
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991874"),
                            ConcurrencyStamp = "c9d4c053-49b6-410c-bc78-2d54a9991875",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("role_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("user_claims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("user_logins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991873"),
                            RoleId = new Guid("c9d4c053-49b6-410c-bc78-2d54a9991874")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("user_tokens", (string)null);
                });

            modelBuilder.Entity("Freshmart.Infrastructure.Data.DbEntities.Product", b =>
                {
                    b.HasOne("Freshmart.Infrastructure.Data.DbEntities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Freshmart.Infrastructure.Data.DbEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Freshmart.Infrastructure.Data.DbEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Freshmart.Infrastructure.Data.DbEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Freshmart.Infrastructure.Data.DbEntities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Freshmart.Infrastructure.Data.DbEntities.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
